import "dotenv/config";
import { getSupabase } from "./db";

const rawData = [
  { day: 1, newcomer: "Connect your wallet in the BaseQuest app → Tap the button to instantly claim your free yourname.base.eth subdomain (takes ~10 seconds, no gas needed yet)", builder: "Tap “1-Click Deploy” → Launch a “Hello World” smart contract using thirdweb template (fully guided, no code)", creator: "Post on X or Farcaster: “GM Base! Just started BaseQuest 🚀 @base” + screenshot your connected wallet", defi: "Swap any small amount ($1+) on Uniswap or Aerodrome on Base (use in-app swap button)" },
  { day: 2, newcomer: "Bridge $1–$10 from Ethereum Mainnet to Base using the official Base bridge (link + guide in app)", builder: "Mint a free daily NFT on Zora (100% free, in-app mint button)", creator: "Create/post a simple Base meme (use Canva templates in app) with #BaseQuest @base", defi: "Add $5+ liquidity to any pool on Aerodrome (top DEX on Base, in-app 1-click)" },
  { day: 3, newcomer: "Follow @base & @jessepollak on X, turn on notifications for updates", builder: "Deploy your own fun ERC-20 memecoin (ready template, name it anything – no coding required)", creator: "Write a quick 3-post thread on X/Farcaster: “Why I’m excited about Base in 2025” – tag @base", defi: "Buy $5+ of a top memecoin like $BRETT or $TOSHI (DexScreener link in app for trending)" },
  { day: 4, newcomer: "Send a tiny amount (0.0001 ETH ~$0.30) to a friend on Base (paste their address in app)", builder: "Register a free custom .base domain at basenames.xyz (in-app guide)", creator: "Post screenshot of your first Base transaction: “Officially based ⚡ @base”", defi: "Provide liquidity on Aerodrome (any pair, even $10+) – screenshot the added LP" },
  { day: 5, newcomer: "Add Base network to your wallet (Coinbase Wallet or MetaMask – 1-tap guide in app)", builder: "Deploy a simple onchain guestbook contract (template: anyone can sign it forever)", creator: "Record a 7-second Reel/TikTok video: “I’m building on Base now!” – tag @base", defi: "Deposit $20+ into Moonwell or Seamless (lend stablecoins for yield)" },
  { day: 6, newcomer: "Turn on Base chain in Phantom, Rabby, or Rainbow wallet (step-by-step in app)", builder: "Mint your first free media NFT on Zora or Sound Protocol", creator: "Post a blurred portfolio screenshot: “Feeling super based 🟦” + short caption", defi: "Buy a cheap social key or item on a Base app (friend.tech-style if active)" },
  { day: 7, newcomer: "Set your profile picture & display name in the BaseQuest app (make it fun!)", builder: "Deploy your first Farcaster Frame: “Completed Week 1 of BaseQuest 🗿” (template ready)", creator: "Post: “Hit my 7-day streak! Tag 3 friends to join me on Base @base”", defi: "Start farming points/yield on Moonwell (deposit USDC or ETH)" },
  { day: 8, newcomer: "Claim any free “Base Citizen” or ecosystem NFT (check in-app daily drops)", builder: "Launch a small 1/1 NFT edition on Zora (you’re now an artist!)", creator: "Create & post a “Base vs other chains” speed/low-fee meme @base", defi: "Snipe or buy a trending new memecoin on Aerodrome or Uniswap (e.g. fresh $DEGEN play)" },
  { day: 9, newcomer: "Bridge a small amount from another L2 (Arbitrum/Optimism) to Base", builder: "Deploy a simple onchain poll contract: “Which memecoin wins 2025?”", creator: "Post your Day 9 streak screenshot: “9 days strong on Base!” – tag @base", defi: "Supply assets on Seamless or Aave on Base (borrow if you want leverage)" },
  { day: 10, newcomer: "Invite 1 friend via your referral link (they just sign up – both get bonus XP)", builder: "Deploy a “gm()” function contract that tips you when people call it", creator: "10-post thread: “What I’ve done in my first 10 days on Base” – tag @base", defi: "Buy a classic or top Base memecoin ($BRETT, $TOSHI, $DEGEN)" },
  { day: 11, newcomer: "Find or make a Base meme & post it on X with #BaseQuest @base", builder: "Follow a thirdweb/Base tutorial → deploy a basic interactive contract", creator: "Post wallet screenshot (blur balances): “Day 11 streak going strong!” – tag friends", defi: "Swap $10+ on Aerodrome (best rates on Base)" },
  { day: 12, newcomer: "Reply positively to 5 Base-related posts on X or Farcaster (spread good vibes!)", builder: "Join Base Discord → ask 1 genuine question in #dev-help channel", creator: "Create a quick X poll: “What’s your favorite thing about Base?” – tag @base", defi: "Add liquidity to a top pair like $BRETT/WETH on Aerodrome" },
  { day: 13, newcomer: "Post: “Base fees are insanely low – game changer!” + add a meme", builder: "Mint a Zora NFT → explore its contract on Basescan (learn how it works)", creator: "Share your favorite Base project (e.g. Aerodrome, Zora) + why – tag project & @base", defi: "Farm yield on Moonwell (deposit stablecoins for safe points)" },
  { day: 14, newcomer: "Like & repost 10 Base ecosystem posts today (easy engagement!)", builder: "Sketch your first mini-app idea (paper, Figma, or notes – no code yet)", creator: "Post 2-week streak proof + your leaderboard rank @base", defi: "Open a small perpetuals or leveraged position on a Base DEX" },
  { day: 15, newcomer: "Claim any free “Mid-Month” or ecosystem NFT drop in app", builder: "Deploy a contract with a fun hidden onchain message for discoverers", creator: "Create a meme about a fake $QUEST token & post it everywhere", defi: "Bridge $50+ from any chain to Base (grow your stack!)" },
  { day: 16, newcomer: "Join the official Base Discord → say GM or introduce yourself in #general", builder: "Deploy a mini onchain lottery (people enter with tiny ETH)", creator: "Short thread or video teaching one early quest to newbies", defi: "Ape into the current top 24h gainer on Base (check DexScreener in app)" },
  { day: 17, newcomer: "Mint today’s free daily NFT on Zora (creator-focused drops)", builder: "Add a “Tip me on Base” button to your X bio (code snippet in app)", creator: "Post comparison: “My wallet age vs my BaseQuest level/XP”", defi: "Stake ETH or wrapped assets on a Base protocol for yield" },
  { day: 18, newcomer: "Switch to or set up Coinbase Smart Wallet (smoothest Base experience)", builder: "Deploy an onchain “digital will” (fun inheritance logic)", creator: "Aim for 50+ likes on a Base-related post today", defi: "Trade a perpetual future on a Base-supported DEX" },
  { day: 19, newcomer: "Help 3 friends complete today’s Beginner quest (share referral + tips)", builder: "Deploy a contract that mints free NFTs when someone sends ETH", creator: "Post: “Unbroken streak – loving BaseQuest so far 🗿” + proof", defi: "Play a prediction market or event bet using Base assets" },
  { day: 20, newcomer: "Claim your 20-day OG role or badge in Base Discord/community", builder: "Launch a free small PFP or edition NFT collection on Zora", creator: "Make a TikTok/Reel about your BaseQuest progress (aim for shares/views)", defi: "Farm a hot yield vault or points program on Base (e.g. Aerodrome/Moonwell)" },
  { day: 21, newcomer: "Mint a 3-week celebration or milestone NFT (free in app)", builder: "Deploy a contract with built-in referral rewards", creator: "Host a quick 5-min X Space: “Why Base is dominating 2025”", defi: "Open a fun high-leverage long on a memecoin (screenshot PnL)" },
  { day: 22, newcomer: "Bridge assets from Optimism or another OP Stack chain to Base", builder: "Deploy a mini onchain leaderboard for you & friends", creator: "Post a “love letter” to @jessepollak or Base team on Farcaster/X", defi: "Supply/borrow on Seamless or Moonwell for optimal yield" },
  { day: 23, newcomer: "Find & claim a working Base ecosystem faucet or free drop", builder: "Deploy a token-gated simple page (only Base NFT holders enter)", creator: "Create a meme aiming for reposts by Base influencers/KOLs", defi: "Buy a cheap Base NFT (under $10 on Zora)" },
  { day: 24, newcomer: "Send or create an onchain “resume” or profile (use tools like basedresume)", builder: "Deploy a contract that pays tiny tips for “GM” messages", creator: "Thread ranking your current top 10 Base projects (Aerodrome, Zora, etc.)", defi: "Use concentrated liquidity ranges on Aerodrome for better rewards" },
  { day: 25, newcomer: "Mint a holiday/seasonal 2025 Base or Zora NFT (free drops common)", builder: "Launch a fun 0% tax memecoin just for the culture", creator: "Post full streak + wallet proof: “25 days based @base”", defi: "Stake in a Base restaking or liquid staking protocol" },
  { day: 26, newcomer: "Help a family member or friend set up a Base wallet (onboard someone new!)", builder: "Deploy a festive onchain advent calendar or daily drop", creator: "Video: “Day 26 of daily shipping on Base – here’s what I learned”", defi: "YOLO $50+ into a brand-new hyped Base memecoin launch" },
  { day: 27, newcomer: "Claim the “Almost There” badge or drop in app", builder: "Deploy a playful “ragequit” contract that burns tokens on trigger", creator: "Get 100+ likes on any Base-related post today", defi: "Farm the newest hot points or yield program on Base" },
  { day: 28, newcomer: "Send 28 free or cheap Base NFTs to 28 different friends/wallets", builder: "Deploy your own mini version of a BaseQuest-style contract", creator: "Post proof you’re in the top 1,000 global leaderboard", defi: "Bridge exactly $420 (meme amount) to Base & screenshot" },
  { day: 29, newcomer: "Mint the rare “29/30” milestone NFT (limited drop)", builder: "Deploy something completely original that’s never been onchain before", creator: "Write a big $QUEST (or Base future) pitch thread (10+ posts)", defi: "Add liquidity to a trending pool (e.g. top memecoin/WETH)" },
  { day: 30, newcomer: "Claim your legendary Month 1 soulbound NFT & “Base Legend” title", builder: "Deploy the first version of YOUR personal dream app/contract on Base mainnet", creator: "Create a massive 30-post thread or video recap of your entire journey – tag @base + friends", defi: "Donate any memecoin/DeFi profits this month to Base ecosystem grants or builders" },
  { day: 31, newcomer: "Create & post an original Base meme (use Canva or in-app templates) with #OnBase @base", builder: "Tuesday: Join any Base builder X Space (search “Base dev space” or check @base schedule) – stay 15+ min", creator: "Post your monthly portfolio update thread (blur amounts if you want)", defi: "Enter a high-yield vault on Beefy or Extra Finance on Base" },
  { day: 32, newcomer: "Share a Base news article or update + your quick take on X/Farcaster", builder: "Study RainbowKit or Wagmi docs – connect a wallet button in a test project", creator: "Record & post short video (15–30 sec): “What I learned this week on Base”", defi: "Restake your ETH on an EigenLayer-related pool on Base" },
  { day: 33, newcomer: "Post a “Base win” story or screenshot from your activity", builder: "Design your next mini-app idea in Figma or on paper – post the sketch", creator: "Onboard 1 new person (send referral + help them with Day 1)", defi: "Buy/swap into a trending mid-cap Base token (check DexScreener)" },
  { day: 34, newcomer: "Reply thoughtfully to 5+ Base builder threads", builder: "Friday: Join a live Base builder or ecosystem X Space", creator: "Post invite: “Who wants to build on Base together?” tag friends", defi: "Add concentrated liquidity on Aerodrome (set a tight range)" },
  { day: 35, newcomer: "Start a discussion thread: “What’s the most underrated Base project?”", builder: "Deploy a small improvement to a previous contract (e.g. add a new function)", creator: "Create weekly recap video (1–2 min) about your BaseQuest progress", defi: "Borrow stablecoins on Morpho or Aave Base for leverage play" },
  { day: 36, newcomer: "Post daily GM with a unique Base twist (e.g. “GM from the cheapest L2”)", builder: "Record a 30-sec clip of your latest deploy + post it", creator: "Help 2 friends complete a quest today", defi: "Snipe a hyped new memecoin launch on Base" },
  { day: 37, newcomer: "Tuesday bonus: Post live reactions from today’s Base Space", builder: "Tuesday: Actively ask or answer a question in a Base dev Space", creator: "Share your current favorite Base dApp + why", defi: "Farm $AERO or protocol points on Aerodrome" },
  { day: 38, newcomer: "Share a Base tutorial you just followed", builder: "Prototype a simple frontend for one of your contract ideas (use Next.js template)", creator: "Post your growing referral count + thank your squad", defi: "Optimize existing LP position (adjust range or move vault)" },
  { day: 39, newcomer: "Post about a Base feature you love (e.g. account abstraction)", builder: "Deploy an upgraded version of an earlier project", creator: "Short video: “Top 3 Base tools I use daily”", defi: "Supply assets on Compound V3 on Base" },
  { day: 40, newcomer: "Celebrate Day 40: Post streak screenshot + “Still going strong @base”", builder: "Friday: Join Base community Space – introduce yourself if comfortable", creator: "Onboard another newbie + post about it", defi: "Trade a small perps position on a Base DEX" },
  { day: 41, newcomer: "Create a poll: “What should I build next on Base?”", builder: "Work on your weekly mini-app – aim for basic functionality", creator: "Weekly content: Thread ranking new Base launches this week", defi: "Farm a new points program (whatever is hot this week)" },
  { day: 42, newcomer: "Reply to Base KOLs/influencers with value-add comments", builder: "Record dev progress + post short clip", creator: "Grow your Base list or group – invite 5+ people", defi: "Remove/rebalance liquidity for better yields" },
  { day: 43, newcomer: "Tuesday: Post key takeaways from today’s builder Space", builder: "Tuesday: Share what you learned in Space + deploy something small inspired by it", creator: "Post your current leaderboard rank + motivate others", defi: "Long a Base ecosystem token with small leverage" },
  { day: 44, newcomer: "Share a Base meme remix of a viral template", builder: "Add wallet connection to your mini-app prototype", creator: "Video: “How BaseQuest changed my crypto habits”", defi: "Stake in a liquid restaking token (LRT) on Base" },
  { day: 45, newcomer: "Post halfway-to-60 milestone + tag @base", builder: "Deploy your weekly mini-app (even if basic – tip jar, counter, etc.)", creator: "Onboard 2+ people this week – post success story", defi: "Ape carefully into a mid-size Base project token" },
  { day: 46, newcomer: "Discuss Base vs other L2s in a balanced thread", builder: "Friday: Join Space + network with 1 builder (DM or mention)", creator: "Create community shoutout post for active BaseQuest users", defi: "Harvest and compound yields from farms" },
  { day: 47, newcomer: "Post daily Base inspiration quote + image", builder: "Improve UI of your latest deploy (add buttons, styling)", creator: "Weekly video: “My favorite Base projects right now”", defi: "Provide liquidity to a new trending pool" },
  { day: 48, newcomer: "Engage in Base governance or proposal discussions", builder: "Study OnchainKit or thirdweb React components", creator: "Help moderate or answer questions in Base Discord", defi: "Close a perps position + post PnL (win or loss)" },
  { day: 49, newcomer: "Create original Base artwork or edited image", builder: "Tuesday: Prepare & ask a dev question in Space", creator: "Post your referral leaderboard position", defi: "Farm across multiple protocols for max points" },
  { day: 50, newcomer: "Celebrate 50 days: Massive streak post @base + screenshot everything", builder: "Deploy a contract that interacts with an existing Base protocol (e.g. Aerodrome)", creator: "Host your first 5–10 min X Space or reply thread Q&A", defi: "Bridge larger amount ($100+) into Base from another chain" },
  { day: 51, newcomer: "Start a “Base builder spotlight” – shoutout someone cool", builder: "Record full screen share of your latest deploy", creator: "Weekly long-form content: “Month 2 on BaseQuest recap”", defi: "Optimize entire DeFi portfolio for highest safe yield" },
  { day: 52, newcomer: "Post reactions to latest Base ecosystem news", builder: "Friday: Speak up in Space (even just “GM builders!”)", creator: "Onboard 3+ people this week", defi: "Play a prediction market event on Base assets" },
  { day: 53, newcomer: "Create a Base meme series (2–3 connected memes)", builder: "Work on collaborative idea – DM a builder from Space", creator: "Grow your personal Base community (list, group, channel)", defi: "Use flash loan or advanced strategy (if comfortable)" },
  { day: 54, newcomer: "Reply to every Base-related mention of BaseQuest", builder: "Deploy something inspired by community feedback", creator: "Video tutorial: How to complete a hard quest", defi: "Harvest all yields + reinvest smarter" },
  { day: 55, newcomer: "Post “What Base needs next” idea thread", builder: "Tuesday: Co-host or actively participate in Space", creator: "Celebrate referrals hitting double digits", defi: "Long-term stake in Base governance tokens" },
  { day: 56, newcomer: "Share your favorite Base transaction of all time", builder: "Finalize & polish your best mini-app so far", creator: "Weekly video ranking top Base tools/builders", defi: "Remove bad LP positions, consolidate winners" },
  { day: 57, newcomer: "Engage deeply in a Base proposal vote discussion", builder: "Deploy improved version with community-suggested feature", creator: "Post portfolio evolution from Day 1 → now", defi: "Farm the absolute hottest new points meta" },
  { day: 58, newcomer: "Friday bonus: Post live Space takeaways", builder: "Friday: Network + follow 5 new builders", creator: "Host small onboarding session for new referrals", defi: "Responsible leverage play on ecosystem token" },
  { day: 59, newcomer: "Create motivational Base streak meme for others", builder: "Prepare for Day 60 deploy milestone", creator: "Final prep for monthly recap content", defi: "Full portfolio rebalance + screenshot" },
  { day: 60, newcomer: "Massive 60-day celebration post: “2 months based @base” + full recap", builder: "Deploy your most ambitious mini-app yet (functional dApp)", creator: "Publish big monthly video/thread: “60 days of BaseQuest – my transformation”", defi: "Donate portion of yields/profits to Base public goods or builders" },
  { day: 61, newcomer: "Start a daily thread: “What should the next big Base app be?” – get replies", builder: "Deploy a functional mini-dApp with real user interaction (e.g. tip jar used by friends)", creator: "Host your first full 15–30 min X Space about Base building", defi: "Optimize your entire DeFi portfolio across Base protocols for max yield" },
  { day: 62, newcomer: "Tuesday: Live-post key insights & quotes from today’s builder Space", builder: "Tuesday: Speak in a Base dev Space (share a deploy, ask deep question)", creator: "Onboard 5+ new people this week – post group screenshot", defi: "Farm the current hottest points program + compound rewards" },
  { day: 63, newcomer: "Create a viral Base meme series (3+ connected memes)", builder: "Add proper frontend + wallet connection to your best mini-app", creator: "Start or grow a dedicated Base Telegram/Discord group (aim 50+ members)", defi: "Use leverage carefully on a Base ecosystem token perps trade" },
  { day: 64, newcomer: "Debate “Base vs Solana/Ethereum L2s in 2026” in a balanced thread", builder: "Collaborate: DM a builder from Space → plan joint small feature", creator: "Weekly long-form video: “Top 5 underrated Base projects”", defi: "Participate in a Base protocol governance vote" },
  { day: 65, newcomer: "Spotlight a lesser-known Base builder or project (tag them!)", builder: "Deploy an upgrade based on community feedback", creator: "Post monthly portfolio evolution + lessons learned", defi: "Harvest all farms/vaults + reinvest into higher-APY positions" },
  { day: 66, newcomer: "Friday: Post live takeaways + screenshots from Space", builder: "Friday: Host or co-host a 10-min segment in a Base Space", creator: "Run an onboarding session for your referrals/group", defi: "Cross-chain arbitrage or bridge optimization play" },
  { day: 67, newcomer: "Share advanced Base tip (e.g. account abstraction tricks)", builder: "Integrate a real Base protocol (Aerodrome swap, Zora mint) into your dApp", creator: "Video tutorial: “How to deploy your first contract on Base”", defi: "Long-term lock in a high-conviction Base token farm" },
  { day: 68, newcomer: "Post reactions to major Base ecosystem announcement", builder: "Polish UI/UX of your main project (make it shareable)", creator: "Grow community: Run a mini-contest or AMA in your group", defi: "Close leveraged positions + lock profits in stable yield" },
  { day: 69, newcomer: "Tuesday: Host your own short Base discussion thread live", builder: "Tuesday: Demo your latest deploy live in Space", creator: "Collaborate with another creator on a joint post/video", defi: "Snipe a high-potential new memecoin or project launch" },
  { day: 70, newcomer: "Celebrate 70 days: “Still unbroken on BaseQuest @base” + full proof", builder: "Deploy a dApp that at least 5 people interact with (share link)", creator: "Weekly video ranking new Base tools or updates", defi: "Full portfolio audit + rebalance for risk/yield" },
  { day: 71, newcomer: "Daily thought leadership: “Why Base will win consumer apps”", builder: "Start planning a bigger collaborative project with Space friends", creator: "Host regular community event (weekly AMA or build session)", defi: "Advanced yield strategy: Loop borrowing/lending for extra APY" },
  { day: 72, newcomer: "Create Base builder motivation thread for newbies", builder: "Add analytics or onchain events to your dApp", creator: "Onboard 10+ total active members to your group", defi: "Participate in prediction markets with meaningful size" },
  { day: 73, newcomer: "Friday: Summarize week’s Base wins in a mega-thread", builder: "Friday: Lead a small demo or tutorial in Space", creator: "Pro video series episode 1: “My 70-day Base journey”", defi: "Farm multiple points programs simultaneously" },
  { day: 74, newcomer: "Engage in deep governance discussion on Base forums/Discord", builder: "Deploy version with user feedback implemented", creator: "Community milestone post: “We hit X members building on Base!”", defi: "Responsible high-leverage play on trending token" },
  { day: 75, newcomer: "Post “Hidden gems on Base” list (5+ projects)", builder: "Integrate thirdweb or OnchainKit for better UX", creator: "Run referral contest inside your community", defi: "Harvest + donate portion to Base public goods" },
  { day: 76, newcomer: "Tuesday: Live-thread an entire Base dev Space", builder: "Tuesday: Co-host full Base builder Space", creator: "Weekly content: Interview a Base builder (even text works)", defi: "Optimize concentrated LP positions for fees" },
  { day: 77, newcomer: "Share your personal Base “origin story” thread", builder: "Add social features (share button, referrals) to dApp", creator: "Grow group to 100+ members – celebrate publicly", defi: "Stake governance tokens for voting power + rewards" },
  { day: 78, newcomer: "Create educational Base infographic/meme combo", builder: "Deploy mobile-friendly version or frame for your dApp", creator: "Video: “How BaseQuest turned me into a builder”", defi: "Close monthly DeFi cycle + post anonymized PnL recap" },
  { day: 79, newcomer: "Spotlight community member from your group", builder: "Collaborate on joint deploy with another BaseQuest user", creator: "Host large onboarding wave for new users", defi: "Advanced restaking + multiple LRT positions" },
  { day: 80, newcomer: "80-day mega celebration post @base + tag squad", builder: "Launch your most polished dApp yet (share widely)", creator: "Monthly recap video/thread: “80 days of daily Base habits”", defi: "Big (responsible) position in ecosystem governance token" },
  { day: 81, newcomer: "Daily challenge: Predict next big Base narrative", builder: "Fix bugs + add requested features from users", creator: "Run community build-along or challenge", defi: "Harvest all yields + compound aggressively" },
  { day: 82, newcomer: "Friday: Host your own Base discussion Space", builder: "Friday: Demo collaborative project progress", creator: "Collaborate with Base KOL or larger creator", defi: "Use flash loans or complex strategy (if experienced)" },
  { day: 83, newcomer: "Post advanced Base optimization tips", builder: "Integrate payments or NFT minting into dApp", creator: "Community hits major milestone – announce prizes/roles", defi: "Governance proposal comment or support" },
  { day: 84, newcomer: "Create “Base ecosystem map 2025” thread", builder: "Deploy onchain governance or voting feature", creator: "Weekly pro video: Deep dive into one Base protocol", defi: "Full risk assessment + adjust positions" },
  { day: 85, newcomer: "Engage with Base core team posts thoughtfully", builder: "Plan next big project (write spec + post it)", creator: "Host multi-guest Space with community members", defi: "Farm emerging new meta points program" },
  { day: 86, newcomer: "Tuesday: Run live poll during Space", builder: "Tuesday: Present your project roadmap in Space", creator: "Grow influence: Get featured or reposted by Base account", defi: "Leverage ecosystem token for short-term swing" },
  { day: 87, newcomer: "Share “What I wish I knew at Day 1 on Base”", builder: "Deploy major update based on community votes", creator: "Video series finale for month: Lessons + wins", defi: "Donate significant portion to Base builders/grants" },
  { day: 88, newcomer: "Create viral motivational Base video clip", builder: "Collaborate internationally – find cross-timezone builder partner", creator: "Community leadership: Appoint mods or roles", defi: "Optimize for upcoming airdrops/points snapshots" },
  { day: 89, newcomer: "Prep 90-day celebration post", builder: "Final polish on all projects for milestone deploy", creator: "Prep massive 90-day content drop", defi: "Full portfolio screenshot (blurred) + strategy share" },
  { day: 90, newcomer: "Epic 90-day post: “From newbie to Base leader @base” + full journey", builder: "Deploy your flagship project or major contribution (e.g. open-source tool)", creator: "Publish huge 90-day transformation video/thread + community celebration", defi: "Execute pro-level DeFi strategy + share anonymized results" },
  { day: 91, newcomer: "Publish a deep thread: “The future of consumer apps on Base in 2026–2030” – tag @base & key builders", builder: "Open-source one of your best dApps or tools on GitHub (proper README + license)", creator: "Host a major onboarding wave: Aim to bring 10+ active new builders into your community", defi: "Execute a sophisticated yield-looping strategy across 3+ protocols" },
  { day: 92, newcomer: "Spotlight an emerging Base narrative or underrated sector", builder: "Contribute a PR or fix to an existing open-source Base project", creator: "Launch professional video series: “Base Masters” – interview a notable builder", defi: "Vote in multiple Base ecosystem governance proposals" },
  { day: 93, newcomer: "Write a “What Base gets right that others don’t” comparative analysis", builder: "Start a collaborative open-source project with at least 2 other builders", creator: "Grow your community to 200+ active members – announce roles/moderators", defi: "Harvest full quarterly yields + compound into long-term positions" },
  { day: 94, newcomer: "Host a debate thread: “Base’s biggest challenge & how to solve it”", builder: "Deploy a production-ready tool that solves a real pain point for Base builders", creator: "Collaborate with a Base KOL or larger creator on joint content", defi: "Run a multi-leg arbitrage or complex DeFi strategy" },
  { day: 95, newcomer: "Publish your personal “Base Manifesto” – vision for the chain", builder: "Mentor a newer builder: Review their code/deploy and help ship", creator: "Run a week-long community event (build challenge, AMA series)", defi: "Stake significant governance tokens + delegate voting power" },
  { day: 96, newcomer: "Tuesday: Host your own full Base builder X Space (30+ min)", builder: "Tuesday: Demo your open-source contribution live in Space", creator: "Video: “How I built a thriving Base community from scratch”", defi: "Optimize portfolio for upcoming major airdrops/snapshots" },
  { day: 97, newcomer: "Share “Lessons from 97 days of daily Base activity”", builder: "Release v1 of a tool that gets used by 10+ builders", creator: "Community hits 300+ members – celebrate with giveaways/NFTs", defi: "Responsible high-conviction position in Base’s core token" },
  { day: 98, newcomer: "Create an infographic summarizing Base’s growth stats & milestones", builder: "Integrate your tool into another popular Base dApp or dashboard", creator: "Host cross-community Space with another L2 or ecosystem", defi: "Full risk-managed leverage cycle + lock profits" },
  { day: 99, newcomer: "Predict the top 5 Base projects of 2026 in a detailed thread", builder: "Organize a hackathon-style sprint with your collaborators", creator: "Professional content drop: Documentary-style “100 days on Base” teaser", defi: "Donate a meaningful portion of profits to Base public goods funding" },
  { day: 100, newcomer: "Epic 100-day celebration post: “Century club achieved @base” + full timeline", builder: "Deploy or launch your flagship project that you’ve been building for months", creator: "Massive 100-day video/thread: “From zero to Base leader” – inspire thousands", defi: "Execute your most advanced DeFi strategy ever + share framework (anonymized)" },
  { day: 101, newcomer: "Daily mastery: Critique a major Base proposal constructively", builder: "Contribute documentation or tutorials for Base/core tools", creator: "Run leadership handover or train new community moderators", defi: "Full portfolio diversification across Base-native assets" },
  { day: 102, newcomer: "Spotlight the next generation of Base builders (tag rising stars)", builder: "Release v2 of your open-source tool with community contributions", creator: "Collaborate with official Base channels or team members", defi: "Vote as a major delegate in ecosystem governance" },
  { day: 103, newcomer: "Publish “How BaseQuest changed crypto for me forever”", builder: "Mentor multiple builders publicly (code reviews on X/Space)", creator: "Community reaches 500+ members – launch sub-groups or chapters", defi: "Harvest yearly yields + reinvest in long-term ecosystem bets" },
  { day: 104, newcomer: "Host prediction thread: “Base at 1 billion users – what it looks like”", builder: "Deploy a governance or DAO tool for the Base ecosystem", creator: "Pro series finale: “The future of building on Base”", defi: "Advanced cross-protocol strategy involving restaking + leverage" },
  { day: 105, newcomer: "Share your complete Base content archive/thread collection", builder: "Organize or judge a Base community hackathon/event", creator: "Host celebration Space for all long-streak BaseQuest users", defi: "Full legacy planning: Set up onchain will + beneficiary" },
  { day: 106, newcomer: "Tuesday: Co-host official-level Base discussion Space", builder: "Tuesday: Present your major contribution roadmap publicly", creator: "Invite Base core team or Jesse to your community Space", defi: "Optimize for maximum sustainable yield with minimal risk" },
  { day: 107, newcomer: "Create “Base Hall of Fame” thread nominating legendary builders", builder: "Release a tool that becomes widely adopted in the ecosystem", creator: "Launch sustainable community treasury or funding system", defi: "Donate significant amount to Base builder grants or education" },
  { day: 108, newcomer: "Reflect: “What I’d tell my Day 1 self about Base”", builder: "Final polish on all open-source repos – add stars encouragement", creator: "Community leadership cemented: Announce long-term vision", defi: "Execute final big conviction play of the program" },
  { day: 109, newcomer: "Prep ultimate celebration post + invite community to join", builder: "Prepare legacy contribution (e.g. endowment, perpetual tool)", creator: "Prep massive collaborative finale content piece", defi: "Full portfolio review + anonymized share with community" },
  { day: 110, newcomer: "Legendary finale post: “110 days. From newbie to Base Master. Thank you @base” + complete journey recap", builder: "Ship your ultimate legacy project or major ecosystem contribution on Base mainnet", creator: "Host grand finale event/Space + publish “The BaseQuest Effect” documentary/thread", defi: "Give back: Donate all final program profits to Base ecosystem builders + public goods" }
];

const categories = [
  { key: "newcomer", xp: 50 },
  { key: "builder", xp: 120 },
  { key: "creator", xp: 100 },
  { key: "defi", xp: 110 }
];

async function seedQuests() {
  const s = getSupabase();
  if (!s) {
    console.error("Supabase not connected");
    return;
  }

  console.log("Starting quest seed...");
  
  // Clear existing quests first as requested "I have cleared the last one"
  // Note: If the user manually cleared it, this is fine. If not, this script upserts.
  // To strictly follow "change everything with day to quest", we'll change the slug format.

  for (const row of rawData) {
    for (const cat of categories) {
      // Changed "day" to "quest" in slug as requested
      const slug = `${cat.key}-quest-${row.day}`;
      const title = (row as any)[cat.key];
      const payload = {
        slug,
        title,
        description: title,
        category: "daily",
        audiencecategory: cat.key, // Lowercase to match Postgres column
        status: "active",
        rewardtype: "xp", // Lowercase
        rewardvalue: cat.xp, // Lowercase
        displayorder: row.day, // Lowercase
        day: row.day,
        createdat: new Date().toISOString() // Lowercase just in case
      };

      const { error } = await s.from("quests").upsert(payload, { onConflict: "slug" });
      if (error) {
        console.error(`Failed to upsert ${slug}:`, error.message);
      } else {
        // console.log(`Upserted ${slug}`);
      }
    }
  }
  console.log("Quest seed completed.");
}

seedQuests();
